# Discussion {-}

This paper has developed two techniques for matrix completion that can then be used to complete individual slices of a tensor. The first technique, an alternating least squares procedure relies upon the Eckart-Young-Mirsky theorem to implement low-rank singular value decomposition. Determining the optimal low rank is a model selection problem that is solved using leave one out cross validation to assess the quality of possible ranks on given datasets. The validity of this technique is tested using simulated datasets where a true low rank is known before it is applied to the actual dataset. Finally, the procedure is applied to the real networks dataset and its performance is evaluated by comparing the fitted values versus the true observed values. Upon noticing certain trends due to outliers in the comparison, a log transformation is conducted on the original dataset and the matrix is once again completed. The second technique constructs a statistical model and uses Gibbs Sampling to iteratively sample values from the parameter's full distributions. It acknowledges the weaknesses of the first technique by including both the sample size and the standard deviation of the observations in each matrix cell in the model. This model ends up being very close to a Generalized Least Squares model and so the sampling procedure for the row and the column factors in the matrix is validated by examining the proximity of the variance of the $\beta$ posterior means in many simulated datasets compared to the variance of the GLS estimator. The paper finally also proposes a solution to extend the two techniques to imputing the tensor iteratively as a whole, rather than individual slices. 

For the empirical results throughout this paper $T \in \mathbb{R}^{100 \times 74 \times 4}$: the most used 100 source ports and their combinations with the most used 74 destination ports are considered. This was constructed by first taking the most used 100 source and destination ports, creating a $100 \times 100 \times 4$ tensor, and then removing the rows and columns where all values were completely missing because those rows and columns would not provide row means and column means respectively to inform the completion techniques. All of the modeling techniques are informed by the exploratory data analysis conducted on the original dataset prior to completion steps.

Application of these completion techniques to the networks dataset provides a reasonable estimate for the four continuous features at every possible port combination in the matrix. This completed tensor provides a basis for detecting anomalies in future data. For instance, new observations for a certain port combination that fall outside a threshold of error for the estimated value in the tensor can be marked as as an anomaly and the source and destination IP may be flagged for further investigation. There are two major limitations of these techniques: 

1. The sheer size of existing and future network data makes the computational efficiency of the techniques a large concern. The techniques would need to provide a reasonable estimate for every cell in a tensor that may extend up to $65535 \times 65535 \times 4$ (65535 is the number of overall ports). Furthermore, billions of observations may eventually become available, so recalculating initial means and standard deviations for the observations of each cell would need to be done carefully and to be completed in a reasonable amount of time. While Gibbs Sampling and alternating least squares have both been shown to be very efficient and are often employed for handling high dimensional and large scale datasets, the potential size of the networks datasets that may be fed into these techniques enforce the absolute need for computational efficiency.

2. The techniques do not consider the specific domain context with which each port is used. For instance, in TCP protocol, port number 22 is Secure Shell (SSH), which is one of the most popular ports for everyday users. Previous domain knowledge could perhaps inform reasonable estimates for each port combination. Some port combinations may be expected to have large byte and packet transfers, while others may be expected to have few transfers overall. Constructing additional models or features that incorporate domain knowledge regarding the particular port combinations will be useful for improving the model's effectiveness in detecting anomalies.